name: Build container release images
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon
      # qdon/glitch
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: ${{ github.ref == 'refs/heads/beta' }}
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      flavor: |
        latest=${{ startsWith(github.ref, 'refs/tags/v4.3.') }}
      tags: |
        type=ref,event=branch
        type=raw,value=latest,enable={{ is_default_branch }}
    secrets: inherit

  build-image-streaming:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon-streaming
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: ${{ github.ref == 'refs/heads/beta' }}
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      flavor: |
        latest=${{ startsWith(github.ref, 'refs/tags/v4.3.') }}
      tags: |
        type=ref,event=branch
        type=raw,value=latest,enable={{ is_default_branch }}
    secrets: inherit
